---
services:
  sonarqube-latest-mcp:
    container_name: sonarqube-latest-mcp
    depends_on:
      - sonarqube-latest
    image: mcp/sonarqube:latest
    restart: unless-stopped
    environment:
      SONARQUBE_HTTP_HOST: 0.0.0.0
      SONARQUBE_HTTP_PORT: 8080
      SONARQUBE_TOKEN: ${SONAR_TOKEN}
      SONARQUBE_TRANSPORT: http
      SONARQUBE_URL: http://sonarqube-latest:9000
    networks:
      - sonarqube-latest-backend
    ports:
      - 19999:8080

  sonarqube-latest:
    container_name: sonarqube-latest
    depends_on:
      - sonarqube-latest-openldap
      - sonarqube-latest-postgres
    image: sonarqube:2026.4.1-enterprise
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-latest-postgres/sonarqube?currentSchema=public
      - SONAR_JDBC_USERNAME=sonar

      # LDAP config

      - SONAR_SECURITY_REALM=LDAP
      - LDAP_URL=ldap://sonarqube-latest-openldap:389
      - LDAP_BINDDN=cn=admin,dc=example,dc=org
      - LDAP_REALM=example.org
      - LDAP_USER_BASE_DN=cn=employees,dc=example,dc=org

      # [LDAP] anchor mapping

      - LDAP_USER_BASEDN=cn=employees,dc=example,dc=org
      - LDAP_USER_REQUEST=(&(objectClass=inetOrgPerson)(uid={login}))

      # [LDAP] group mapping

      - LDAP_GROUP_BASEDN=dc=example,dc=org
      - LDAP_GROUP_REQUEST=(&(objectClass=groupofUniqueNames)(uniqueMember={dn}))
      - LDAP_GROUP_IDATTRIBUTE=cn
    stop_grace_period: 3600s
    networks:
      - sonarqube-latest-backend
    volumes:
      - ./conf:/opt/sonarqube/conf
      - ./data:/opt/sonarqube/data
      - ./extensions:/opt/sonarqube/extensions
      # - ./lib/extensions:/opt/sonarqube/lib/extensions
      - ./logs:/opt/sonarqube/logs

  sonarqube-latest-openldap:
    container_name: sonarqube-latest-openldap
    image: osixia/openldap:1.5.0
    networks:
      - sonarqube-latest-backend

  sonarqube-latest-phpldapadmin:
    container_name: sonarqube-latest-phpldadmin
    depends_on:
      - sonarqube-latest-openldap
    image: osixia/phpldapadmin:0.9.0
    ports:
      - 19998:443  # https://localhost:19998
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=sonarqube-latest-openldap
    networks:
      - sonarqube-latest-backend
      - sonarqube-latest-frontend

  sonarqube-latest-postgres:
    container_name: sonarqube-latest-postgres
    image: postgres:18
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=sonar
    networks:
      - sonarqube-latest-backend
    volumes:
      - var-lib-postgresql-18-docker:/var/lib/postgresql/18/docker

  sonarqube-latest-nginx:
    container_name: sonarqube-latest-nginx
    depends_on:
      - sonarqube-latest
    image: nginx:1.29
    networks:
      - sonarqube-latest-backend
      - sonarqube-latest-frontend
    ports:
      - 19995:80
      - 19996:81
      - 19997:443
    volumes:
      - ./server.crt:/etc/nginx/ssl/certificate.crt
      - ./server.key:/etc/nginx/ssl/private.key
      - ./nginx.conf:/etc/nginx/nginx.conf

  # sonarqube-latest-vmagent:
  #   container_name: sonarqube-latest-vmagent
  #   depends_on:
  #     - sonarqube-latest
  #   image: victoriametrics/vmagent:v1.93.15
  #   networks:
  #     - sonarqube-latest-backend
  #   command:
  #     - "--promscrape.config=/etc/prometheus/prometheus.yml"
  #     - "--remoteWrite.url=http://host.docker.internal:8428/api/v1/write"
  #   volumes:
  #     - ./vmagent.yaml:/etc/prometheus/prometheus.yml
  #     - vmagentdata:/vmagentdata

networks:
  sonarqube-latest-backend:
  sonarqube-latest-frontend:

volumes:
  var-lib-postgresql-18-docker:
  # vmagentdata:
